packages:
  - 'packages/*'
  - 'e2e'
  - 'e2e/test/*'
minimumReleaseAge: 4320 # 3 days, see: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAgeExclude:
  # Renovate security update: axios@1.13.5
  - axios@1.13.5
  # Renovate security update: @sveltejs/kit@2.52.2 || 2.53.3
  - "@sveltejs/kit@2.52.2 || 2.53.3"
  # Renovate security update: svelte@5.51.5 || 5.53.5
  - svelte@5.51.5 || 5.53.5
  # Renovate security update: ajv@8.18.0
  - ajv@8.18.0
  # Renovate security update: minimatch@10.2.4
  - minimatch@10.2.4
